# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(735, 395)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 350, 201, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#C10020;\n"
"}\n"
"void MainWindow::on_pushButton_clicked()\n"
"{\n"
"    ui->pushButton->setStyleSheet(\"background-color: #C10020;\");\n"
"\n"
"    QTimer::singleShot(1000, this, [=]() {\n"
"        ui->pushButton->setStyleSheet(\"background-color: #C10020;\");\n"
"    });\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 741, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../OneDrive/Изображения/Пленка/photo_2026-01-29_09-07-46.jpg"))
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 270, 291, 51))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #002f55;\n"
"    color: #81D4FA;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #81D4FA;\n"
"}\n"
"void MainWindow::on_pushButton_clicked()\n"
"{\n"
"    ui->pushButton->setStyleSheet(\"background-color: #81D4FA;\");\n"
"\n"
"    QTimer::singleShot(1000, this, [=]() {\n"
"        ui->pushButton->setStyleSheet(\"background-color: #81D4FA;\");\n"
"    });\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 190, 351, 51))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #44abff;\n"
"    color: #0A2540;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0A2540;\n"
"}\n"
"void MainWindow::on_pushButton_clicked()\n"
"{\n"
"    ui->pushButton->setStyleSheet(\"background-color: #0A2540;\");\n"
"\n"
"    QTimer::singleShot(1000, this, [=]() {\n"
"        ui->pushButton->setStyleSheet(\"background-color: #0A2540;\");\n"
"    });\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_5.setText(_translate("Form", "EXIT"))
        self.pushButton_6.setText(_translate("Form", "Settings"))
        self.pushButton_7.setText(_translate("Form", "Play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
